### ISSUE TITLE
README files

### ISSUE THREAD

**Issue by zhengp0** [ihmeuw-msca/pyDisagg#5]
Currently in the repository, there are `README.rst` and `readme.md`. I think we should remove `README.rst` and change name `readme.md` to `README.md` to follow the convention.

Afterwards, we also need to change
https://github.com/ihmeuw-msca/splitting-python-package/blob/main/setup.cfg#L5-L6
to the corresponding file and format.

**Comment by AHsu98** [comment]
It looks right in the linked file, I tried to capitalize afterwards, but git doesn't seem to notice it. Let's see if it gets propagated on next push.

**Comment by zhengp0** [comment]
Thanks for working on this @AHsu98! I think the better way to work on these issues is to create a new branch (for example in this case it can be `readme_files`) and make the changes in the branch. Afterwards submit a PR so that the collaborator can comments and contribute. This way it will keep the changes regarding to this issue contained while `main` branch remains clean :)

**Comment by AHsu98** [comment]
Fixed with #13
