### ISSUE TITLE
Split val ==0 but se != 0

### ISSUE THREAD

**Issue by saalUW** [ihmeuw-msca/pyDisagg#52]
Doesn't split, matrix non inv. rate or log odds

**Comment by zhengp0** [comment]
Hi @saalUW and @AHsu98, this is an interesting case. Currently we mark this as illegal
https://github.com/ihmeuw-msca/pyDisagg/blob/main/src/pydisagg/ihme/splitter.py#L132
Along with #53, I am curious what makes this happen. For example, if the value to be split is prevalence and is 0, it means that there are 0 cases in the population they are considering, how do they measure se?
