### ISSUE TITLE
Overlapping ages in data

### ISSUE THREAD

**Issue by saalUW** [ihmeuw-msca/pyDisagg#54]
crashing if there is overlap in similar studies

**Comment by saalUW** [comment]
after some testing, a duplicated row with original age range 40 - 44 changed to 20 - 50 passes, but 41 -43 doesn't.

**Comment by zhengp0** [comment]
Thanks very much @saalUW! Do you have a simple example that can replicate the bug/error. I have a bit of time and work on fixing this :)

**Comment by saalUW** [comment]
Solved in last merge
